name: Cypress Test

on:
  push:
    branches: [ master ]

jobs:
  cypress-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        cd cypress/e2e/pom
        npm ci

    - name: Run Cypress tests
      uses: cypress-io/github-action@v4
      with:
        browser: chrome
        spec: 'cypress/e2e/pom/**/*.cy.js'
